[package]
name = "moho_game"
version = "0.1.0"
edition = "2024"

[dependencies]
moho_core = { path = "../moho_core" }
moho_render_api = { path = "../moho_render_api" }
bincode = { workspace = true }
glam = { workspace = true }
legion = { workspace = true }
log = { workspace = true }
noise = { workspace = true }
serde = { workspace = true, features = ["derive"] }
