[package]
name = "moho_game"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
moho_core = { path = "../moho_core" }
moho_render_api = { path = "../moho_render_api" }
bincode = { workspace = true }
glam = { workspace = true }
tracing = { workspace = true }
noise = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
