[package]
name = "moho_core"
version = "0.1.0"
authors = ["Justin Moore <jmoore5268@gmail.com>"]
edition = "2018"

[dependencies]
glam = { workspace = true }
vulkano = { workspace = true, default-features = true }
vulkano-shaders = { workspace = true }
winit = { workspace = true, default-features = true }
rand = { workspace = true }
