version: '3.8'
services:
  builder:
    build:
      context: ../..
      dockerfile: .github/docker/Dockerfile
    volumes:
      - ..:/work:cached
    working_dir: /work
    command: bash -c "cargo --version && rustc --version"
