[package]
name = "moho_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
moho_core = { path = "../moho_core" }
moho_render_api = { path = "../moho_render_api" }
bytemuck = { workspace = true, features = ["derive"] }
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
glam = { workspace = true }
legion = { workspace = true }
bincode = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
moho_game = { path = "../moho_game" }
naga = { workspace = true, features = ["wgsl-in"] }
tempfile = "3.5"

[features]
wgpu-experimental = []
