[package]
name = "moho_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
moho_core = { path = "../moho_core" }
bytemuck = { workspace = true, features = ["derive"] }
wgpu = { workspace = true, optional = true }
winit = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
glam = { workspace = true }
legion = "0.4"
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
log = { workspace = true }
thiserror = "1.0"

[dev-dependencies]
naga = { workspace = true, features = ["wgsl-in"] }
tempfile = "3.5"

[features]
backend-wgpu = ["wgpu", "winit", "pollster"]
wgpu-experimental = []
