[package]
name = "moho_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
moho_core = { path = "../moho_core" }
bytemuck = { workspace = true, features = ["derive"] }
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
glam = { workspace = true }
legion = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
naga = { workspace = true, features = ["wgsl-in"] }
tempfile = "3.5"

[features]
wgpu-experimental = []
