[package]
name = "moho_level"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
moho_render_api = { path = "../moho_render_api" }
glam = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
gltf = { workspace = true }

[dev-dependencies]
moho_physics = { workspace = true }
glam = { workspace = true }
moho_render_api = { path = "../moho_render_api" }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
